### ISSUE TITLE
Recent Episodes CSS Style is loaded everywhere

### ISSUE THREAD

**Issue by goaround** [CastosHQ/Seriously-Simple-Podcasting#591] opened 2021-01-21 16:15 UTC
**Describe the bug**
The Recent Episodes CSS File is loaded on every page load. Please only load the CSS if they are really shown.

See: https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/fe171a215989d9cd665cbffc326580882bda1952/php/classes/controllers/class-episode-controller.php#L31

**Solution**

Move `wp_enqueue_style( 'ssp-recent-episodes' );` to `render_episodes`

**Comment by goaround** [comment] 2021-01-21 16:17
PR: https://github.com/CastosHQ/Seriously-Simple-Podcasting/pull/592

**Comment by jonathanbossenger** [comment] 2021-01-25 07:17
this is a duplicate of #561

**Comment by jonathanbossenger** [comment] 2021-02-15 09:36
@goaround can you confirm you have tested this fix? I'm testing it now, and moving the `wp_enqueue_style` to the `render_episodes` method does not render the recent-episodes.css. 

Also, it should probably be enqueued in the `render_recent_episodes` method, not the `render_episodes` method, but moving the `wp_enqueue_style` there also does not render the recent-episodes.css.

**Closed** 2024-04-08 16:55 UTC
