### ISSUE TITLE
Player does not record statistics

### ISSUE THREAD

**Issue by renzodangelo** [CastosHQ/Seriously-Simple-Podcasting#573] opened 2020-12-16 11:27 UTC
I have been doing several tests, and apparently, the reproductions are not recorded in any of the audio players of any of my pages (I have 4 podcasts in different websites) I tried with the default player and with the htlm, also with unknown connections, with different browsers and plays are not logged.

[Screencast](https://vimeo.com/491581063/cfc7b71d23)

In the video, I show you the statistics before the [reproduction of an episode] (https://renzodangelo.me/forma-tu-propia-manada/) in the Player in Firefox, and as you can see, it does not register the reproductions. I have done this same test from other browsers, as incognito with session, clearing cache, and in no case does it record the statistics.

The same happens in the 4 sites where I have installed the plugin and with all the audios. The sites have in common the latest version of WP 5.6, Genesis 3.3.3. (With the [Support plugin of SSP](https://wordpress.org/plugins/seriously-simple-podcasting-genesis-support/) I have also turned this off and the problem continues)

This flaw is present exactly from update 2.5. It's a terrible flaw, especially since on my sites, most of the views come from their web pages.

**Comment by renzodangelo** [comment] 2020-12-20 15:33
Hi Jonathan,

In all the sites where I use the plugin, it is presenting the same problem, (the player's reproductions are NOT recorded in the statistics), here are some episodes where the Player is.

https://cotel.com.co/la-nueva-realidad-de-la-inteligencia-artificial/
https://coolcar.store/que-haces-si-el-compresor-de-tu-carro-cruje/
https://renzodangelo.me/forma-tu-propia-manada/

On this page I left the Player without any CSS customization to rule out that it was some of my settings and it doesn't work either, as I indicated in case, the statistics do not work with the standard compact Player either.

https: interna.live/kit-esencial-para-la-instalacion/

I will be awaiting any request from you, thanks and greetings.

**Comment by jonathanbossenger** [comment] 2020-12-21 07:21
Hi, @renzodangelo thanks for all the detailed information. We do have this on our list, but please bear with us, as we're on short staff this time of year.

For now, I would recommend rolling your plugin version back to 2.4.2, so that it can maintain the stats logging until we can get this resolved.

You can use this plugin to rollback plugin versions - https://wordpress.org/plugins/wp-rollback/

Thanks

**Comment by renzodangelo** [comment] 2020-12-21 16:11
Hi Jonathan,

I updated the version that came out today of the Stats plugin and the problem continued. So, I did what you asked me, reverse the version on all sites to 2.4.2 and the problem was fixed immediately.

I wasted a lot of time fixing the old Player CSS, however now everything works.

Thanks for the recommendation, and for the plugin (I did not know it). This error is very serious for those of us who receive the highest number of reproductions via the web. I will be here very attentive to the correction as I need to update to the latest version. Greetings and thanks again.

**Comment by jonathanbossenger** [comment] 2021-01-05 14:31
@renzodangelo we have a fix for this issue ready, could I prepare it as a beta version, with installation instructions, for you to test this, to make sure the problem is resolved?

**Comment by renzodangelo** [comment] 2021-01-05 17:00
@jonathanbossenger Great, I can try it on one of my lower traffic sites.

**Comment by jonathanbossenger** [comment] 2021-01-07 08:51
@renzodangelo thanks.

Please follow this link for the testable version, as well as instructions for how to install it on your site.

https://github.com/CastosHQ/Seriously-Simple-Podcasting/releases/tag/2.5.3-alpha

Please report back here if this resolves the issue.

**Comment by renzodangelo** [comment] 2021-01-07 13:05
Hi @jonathanbossenger,

I have already installed and tested it on a test site and it works fine, that is, browser statistics are recorded correctly =)

**Comment by jonathanbossenger** [comment] 2021-01-08 13:18
Thanks @renzodangelo we have a few other items from the 2.5.0 update we're working on, so please bear with us while we fix those, and then we'll push out an update for the plugin.

**Comment by renzodangelo** [comment] 2021-01-08 20:57
Hi @jonathanbossenger, thanks for answering me. For now, I am using version 2.4.2 that you recommended to me in all my active sites, and I will be waiting for the new version, greetings.

**Closed** 2021-02-10 07:33 UTC
